[Variables]

; [[[ Global Settings ]]]
oDisableDebug = 1
oTheme =custom
oLanguage = english
oUserDir = %USERPROFILE%\awesome\
oBarFixed =1

oBarAutoHide =0
; Delay between placing the cursor on the top area and showing the bar. (In miliseconds)
oBarShowDelay = 300
oBarHeight =32
oBarOffset = 0
; This is the amount of space reserved on top of the screen if bar is in FixedMode
oReservedSpace =32

; If set to 1, Awesome will not try to update colors based on your background ( using #vDesktopBG1# etc...)
oDisableDesktopColors = 1
; If set to 1, the bar background will not get the color from the maximized window titelbar
oDisableTitlebarBlend = 0
; If set to 1, will disable the background change when maximizing a window
oDisableFocusMode = 0
; If all modes are set to 0, how the fuck we get color contrast?
; Well, ask the user what he wants
; Options: 1 = LightMode, 0 = DarkMode
oDefaultColorMode = 0

; Remove the name of the window from the left?
oHideProcessName = 0
; Disable and Hide clock?
oHideClock = 0

; Media Player options: WebNowPlaying | NowPlaying
; WebNowPlayer doesn't need a oMediaPlayerName
; NowPlaying Playaer Name Options: AIMP | CAD | MediaMonkey | Winamp | WMP | WLM | iTunes
;   AIMP |                   CAD                   | MediaMonkey | Winamp |        WMP         |      WLM       | iTunes 
;  ------|-----------------------------------------|-------------|--------|--------------------|----------------|-------- 
;   AIMP | foobar2000                              | MediaMonkey | Winamp | WindowsMediaPlayer | Last.fm Client | iTunes 
;        | J. River Media Center and Media Jukebox |             |        |                    | TTPlayer       |        
;        | MusicBee                                |             |        |                    | OpenPandora    |        
;        |                                         |             |        |                    | Zune           |        

oMediaPlayer = WebNowPlaying
oMediaPlayerName = CAD
