[Variables]

; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;                     STRUCTURE VARIABLES
; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

; Changes the skin transparency type to blur when it's beeing dragged.
awvPerformanceMode = false 
awvLocale=pt-BR

; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;                     BAR VISUALS
; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

; Total Heihgt of the bar / Height where modules will be displayed
awvBarHeight = 32 
awvModuleY = 38
; Background of the bar when nothing is maximized
awvTransparencyType = "None" 
; Border of the bar
awvBarBorder = "None" 
; RGBA Color of the border
awvBorderTint = 0,0,0,0 
; RGBA Color tint for the bar 
awvBarTint= 0,0,0,0
; Icon spacing / Item padding
awvBarSpacing = 32
awvItemPadding=16
; Offset icons from the topbar - Only usefull if using an offset iconpack
awvOffset = 0
; Icons Size
awvBarIconSize = 32
; Dark / White text colors
awvDarkColor = 0,0,0
awvLightColor = 255,255,255

; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;                     MODULE VISUALS
; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

    ;General
; max size of modules (in px)
awvModuleW = 400
; Corner radius for elements
awvWidgetCorners = 6

    ;MediaPlayer
; Amount of blur for MediaPlayerBackground
awvMPBlur = 10
; Where should the colors be collected :: Desktop or File (file is album cover.)
awvMPColorMode = File

