[Variables]

; [[[ Global Settings ]]]
oDisableDebug = 0
oTheme = "default"
oLanguage = english
oUserDir = %USERPROFILE%\awesome\
oBarFixed = 1
oBarAutoHide = 0
oHideClock = 0
oBarHeight = 32
oBarOffset = 0
;  Should the window processname be shown on the Bar?
oHideProcessName = 0
; If set to 1, Awesome will not try to update colors based on your background ( using #vDesktopBG1# etc...)
oDisableDesktopColors = 0
; If set to 1, the bar background will not get the color from the maximized window titelbar
oDisableTitlebarBlend = 0
; If set to 1, will disable the background change when maximizing a window
oDisableFocusMode = 0

; Media Player options: WebNowPlaying | NowPlaying
; WebNowPlayer doesn't need a oMediaPlayerName
; NowPlaying Playaer Name Options: AIMP | CAD | MediaMonkey | Winamp | WMP | WLM | iTunes
;   AIMP |                   CAD                   | MediaMonkey | Winamp |        WMP         |      WLM       | iTunes 
;  ------|-----------------------------------------|-------------|--------|--------------------|----------------|-------- 
;   AIMP | foobar2000                              | MediaMonkey | Winamp | WindowsMediaPlayer | Last.fm Client | iTunes 
;        | J. River Media Center and Media Jukebox |             |        |                    | TTPlayer       |        
;        | MusicBee                                |             |        |                    | OpenPandora    |        
;        |                                         |             |        |                    | Zune           |        

oMediaPlayer = WebNowPlaying
oMediaPlayerName = CAD
