[AlignLeft]
X                = #tIconMargin#R

[AlignRight]
X                = (-(#tIconMargin#+#tIconSize#))r

[SettingsH1]
FontFace         = Segoe UI
FontSize         = 20

FontColor        = 255,255,255
Antialias        = 1


[SettingsH2]
FontFace         = Segoe UI
FontSize         = 12
FontColor        = 255,255,255
FontWeight       = 700
Antialias        = 1

[SettingsH3]
FontFace         = Segoe UI
FontSize         = 10
FontColor        = 255,255,255
Antialias        = 1

[SettingsLabel]
FontFace         = Segoe UI
FontSize         = 12
FontColor        = 255,255,255
Antialias        = 1

[SettingsHint]
FontFace         = Segoe UI
FontSize         = 8
FontColor        = 104,104,104
Antialias        = 1
