[Variables]
; If all modes are set to 0, how the fuck we get color contrast?
; Well, ask the user what he wants
; Options: 1 = LightMode, 0 = DarkMode
tDefaultColorMode = 0

tBarTint = 0,0,0,0
tBarOpacity = 0
tBarStrokeWidth = 0
tBarStrokeColor = 0,0,0
tBarShouldBlur = 1
tBarBlurType = Acrylic
tBarShadow = "None"


tIconSize = 16
tIconMargin = 16

; Colors for when using DefaultColorMode or Focusmode with TitlebarBlend
tBackgroundColor    = 0,0,0

tLightModeTextColor = 0,0,0,255 
tLightModeHoverColor = 255,255,255

tDarkModeTextcolor  = 255,255,255,255
tDarkModeHoverColor = 35,35,35
